version: '3.7'

networks:
  custom:

services:
  #nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/log:/var/log/nginx/
      - ./docker/nginx/config/sites-available:/etc/nginx/sites-available
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - mongo
    networks:
      - custom

  #mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    tty: true
    user: '1000'
    ports:
      - "27017:27017"
    volumes:
      - ./docker/db/lib:/data/db
      - ./docker/db/log:/var/log/mongodb
    networks:
      - custom
  #php
  php:
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - '9000'
    networks:
      - custom